export enum Permission {
  VIEW_USERS = 'view:users',
  MANAGE_USERS = 'manage:users',
  VIEW_ROLES = 'view:roles',
  MANAGE_ROLES = 'manage:roles',
  VIEW_PROFIT = 'view:profit',
  VIEW_BLACKLISTS = 'view:blacklists',
  MANAGE_BLACKLISTS = 'manage:blacklists',
  SEND_SLACK_SERVER_MESSAGE = 'send:slack:server:message',
  EXEC_SCHEDULE_WITH_NEW_ITEMS = 'exec:schedule:with_new_items',
  EXEC_SCHEDULE_WITH_EXIST_ITEMS = 'exec:schedule:with_exist_items',
  VIEW_INFERENCE_NASDAQ = 'view:inference:nasdaq',
  VIEW_INFERENCE_COIN_MAJOR = 'view:inference:coin:major',
  VIEW_INFERENCE_COIN_MINOR = 'view:inference:coin:minor',
  TRADE_NASDAQ = 'trade:nasdaq',
  TRADE_COIN_MAJOR = 'trade:coin:major',
  TRADE_COIN_MINOR = 'trade:coin:minor',
}
