---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
  DB_SECRET: {{ include "db.secret" . | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKey | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretKey | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.auth.google.id | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.auth.google.secret | b64enc | quote }}
  NOTIFY_SECRET_KEY: {{ .Values.notify.secretKey | b64enc | quote }}
  NOTIFY_CHANNEL: {{ .Values.notify.channel | b64enc | quote }}
  OPENAI_PROJECT: {{ .Values.openai.project | b64enc | quote }}
  OPENAI_SECRET_KEY: {{ .Values.openai.secretKey | b64enc | quote }}
  UPBIT_ACCESS_KEY: {{ .Values.upbit.accessKey | b64enc | quote }}
  UPBIT_SECRET_KEY: {{ .Values.upbit.secretKey | b64enc | quote }}
