---
name: Lint

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        project:
          - api
          - ui
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          cache: pnpm
          cache-dependency-path: ${{ matrix.project }}/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ${{ matrix.project }}
        run: pnpm i --frozen

      - name: Run lint
        working-directory: ${{ matrix.project }}
        run: pnpm lint
